// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TouchBase.API.Data;

#nullable disable

namespace TouchBase.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TouchBase.API.Models.Entities.AddressDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("AddressType")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Fax")
                        .HasColumnType("longtext");

                    b.Property<int>("MemberProfileId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("longtext");

                    b.Property<string>("Pincode")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MemberProfileId");

                    b.ToTable("address_details", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlbumCategoryText")
                        .HasColumnType("longtext");

                    b.Property<string>("Beneficiary")
                        .HasColumnType("longtext");

                    b.Property<string>("CategoryId")
                        .HasColumnType("longtext");

                    b.Property<string>("CostOfProject")
                        .HasColumnType("longtext");

                    b.Property<string>("CostOfProjectType")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("IsSubGrpAdmin")
                        .HasColumnType("longtext");

                    b.Property<string>("MemberIds")
                        .HasColumnType("longtext");

                    b.Property<string>("ModuleId")
                        .HasColumnType("longtext");

                    b.Property<string>("NumberOfRotarian")
                        .HasColumnType("longtext");

                    b.Property<string>("OtherCategoryText")
                        .HasColumnType("longtext");

                    b.Property<string>("ProjectDate")
                        .HasColumnType("longtext");

                    b.Property<string>("ShareType")
                        .HasColumnType("longtext");

                    b.Property<string>("SubgrpIds")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WorkingHour")
                        .HasColumnType("longtext");

                    b.Property<string>("WorkingHourType")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("albums", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.AlbumPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("album_photos", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnnounDesc")
                        .HasColumnType("longtext");

                    b.Property<string>("AnnounImg")
                        .HasColumnType("longtext");

                    b.Property<string>("AnnounTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("AnnounType")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("ExpiryDate")
                        .HasColumnType("longtext");

                    b.Property<string>("FilterType")
                        .HasColumnType("longtext");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("InputIds")
                        .HasColumnType("longtext");

                    b.Property<string>("IsSubGrpAdmin")
                        .HasColumnType("longtext");

                    b.Property<string>("Link")
                        .HasColumnType("longtext");

                    b.Property<string>("ModuleId")
                        .HasColumnType("longtext");

                    b.Property<string>("PublishDate")
                        .HasColumnType("longtext");

                    b.Property<string>("RegLink")
                        .HasColumnType("longtext");

                    b.Property<string>("RepeatDates")
                        .HasColumnType("longtext");

                    b.Property<string>("SendSMSAll")
                        .HasColumnType("longtext");

                    b.Property<string>("SendSMSNonSmartPh")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("announcements", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.AttendanceMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendanceRecordId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MemberProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceRecordId");

                    b.HasIndex("MemberProfileId");

                    b.ToTable("attendance_members", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttendanceDate")
                        .HasColumnType("longtext");

                    b.Property<string>("AttendanceDesc")
                        .HasColumnType("longtext");

                    b.Property<string>("AttendanceName")
                        .HasColumnType("longtext");

                    b.Property<string>("AttendanceTime")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("attendance_records", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.AttendanceVisitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendanceRecordId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<string>("VisitorName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceRecordId");

                    b.ToTable("attendance_visitors", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BannerDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("BannerImage")
                        .HasColumnType("longtext");

                    b.Property<string>("BannerTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("BannerType")
                        .HasColumnType("longtext");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("banners", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CatName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChapterName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("chapters", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("CharterDate")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("ClubId")
                        .HasColumnType("longtext");

                    b.Property<string>("ClubName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ClubType")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Distance")
                        .HasColumnType("longtext");

                    b.Property<string>("District")
                        .HasColumnType("longtext");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("GovernorEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("GovernorMobile")
                        .HasColumnType("longtext");

                    b.Property<string>("GovernorName")
                        .HasColumnType("longtext");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Lat")
                        .HasColumnType("longtext");

                    b.Property<string>("Longi")
                        .HasColumnType("longtext");

                    b.Property<string>("MeetingDay")
                        .HasColumnType("longtext");

                    b.Property<string>("MeetingTime")
                        .HasColumnType("longtext");

                    b.Property<string>("PresidentEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("PresidentMobile")
                        .HasColumnType("longtext");

                    b.Property<string>("PresidentName")
                        .HasColumnType("longtext");

                    b.Property<string>("SecretaryEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("SecretaryMobile")
                        .HasColumnType("longtext");

                    b.Property<string>("SecretaryName")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Website")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClubName");

                    b.HasIndex("GroupId")
                        .IsUnique();

                    b.ToTable("clubs", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .HasColumnType("longtext");

                    b.Property<string>("CountryName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.DeviceToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Platform")
                        .HasColumnType("longtext");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("device_tokens", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DistrictName")
                        .HasColumnType("longtext");

                    b.Property<string>("DistrictNumber")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("districts", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("DocAccessType")
                        .HasColumnType("longtext");

                    b.Property<string>("DocTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("DocType")
                        .HasColumnType("longtext");

                    b.Property<string>("DocURL")
                        .HasColumnType("longtext");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.DocumentReadStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("IsRead")
                        .HasColumnType("longtext");

                    b.Property<int>("MemberProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReadAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MemberProfileId");

                    b.HasIndex("DocumentId", "MemberProfileId")
                        .IsUnique();

                    b.ToTable("document_read_statuses", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Ebulletin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("EbulletinFileId")
                        .HasColumnType("longtext");

                    b.Property<string>("EbulletinLink")
                        .HasColumnType("longtext");

                    b.Property<string>("EbulletinTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("EbulletinType")
                        .HasColumnType("longtext");

                    b.Property<string>("ExpiryDate")
                        .HasColumnType("longtext");

                    b.Property<string>("FilterType")
                        .HasColumnType("longtext");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("InputIds")
                        .HasColumnType("longtext");

                    b.Property<string>("IsSubGrpAdmin")
                        .HasColumnType("longtext");

                    b.Property<string>("PublishDate")
                        .HasColumnType("longtext");

                    b.Property<string>("SendSMSAll")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("ebulletins", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("DisplayOnBanner")
                        .HasColumnType("longtext");

                    b.Property<string>("EventDate")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EventDesc")
                        .HasColumnType("longtext");

                    b.Property<string>("EventImageId")
                        .HasColumnType("longtext");

                    b.Property<string>("EventTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("EventType")
                        .HasColumnType("longtext");

                    b.Property<string>("EventVenue")
                        .HasColumnType("longtext");

                    b.Property<string>("ExpiryDate")
                        .HasColumnType("longtext");

                    b.Property<string>("FilterType")
                        .HasColumnType("longtext");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("InputIds")
                        .HasColumnType("longtext");

                    b.Property<string>("IsSubGrpAdmin")
                        .HasColumnType("longtext");

                    b.Property<string>("Link")
                        .HasColumnType("longtext");

                    b.Property<string>("MembersIds")
                        .HasColumnType("longtext");

                    b.Property<string>("NotifyDate")
                        .HasColumnType("longtext");

                    b.Property<string>("Option1")
                        .HasColumnType("longtext");

                    b.Property<string>("Option2")
                        .HasColumnType("longtext");

                    b.Property<string>("ProjectName")
                        .HasColumnType("longtext");

                    b.Property<string>("PublishDate")
                        .HasColumnType("longtext");

                    b.Property<string>("QuestionEnable")
                        .HasColumnType("longtext");

                    b.Property<string>("QuestionText")
                        .HasColumnType("longtext");

                    b.Property<string>("QuestionType")
                        .HasColumnType("longtext");

                    b.Property<string>("RegLink")
                        .HasColumnType("longtext");

                    b.Property<string>("RepeatDateTime")
                        .HasColumnType("longtext");

                    b.Property<string>("RsvpEnable")
                        .HasColumnType("longtext");

                    b.Property<string>("SendSMSAll")
                        .HasColumnType("longtext");

                    b.Property<string>("SendSMSNonSmartPh")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VenueLat")
                        .HasColumnType("longtext");

                    b.Property<string>("VenueLon")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EventDate");

                    b.HasIndex("GroupId");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.EventResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerByMe")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("JoiningStatus")
                        .HasColumnType("longtext");

                    b.Property<int>("MemberProfileId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionId")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MemberProfileId");

                    b.HasIndex("EventId", "MemberProfileId")
                        .IsUnique();

                    b.ToTable("event_responses", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.FamilyMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Anniversary")
                        .HasColumnType("longtext");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactNo")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Dob")
                        .HasColumnType("longtext");

                    b.Property<string>("EmailId")
                        .HasColumnType("longtext");

                    b.Property<string>("MemberName")
                        .HasColumnType("longtext");

                    b.Property<int>("MemberProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Particulars")
                        .HasColumnType("longtext");

                    b.Property<string>("Relationship")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MemberProfileId");

                    b.ToTable("family_members", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FeedbackText")
                        .HasColumnType("longtext");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("MemberProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("feedbacks", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .HasColumnType("longtext");

                    b.Property<string>("Address2")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("ClubHistory")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactNo")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("GrpCategory")
                        .HasColumnType("longtext");

                    b.Property<string>("GrpImageId")
                        .HasColumnType("longtext");

                    b.Property<string>("GrpImg")
                        .HasColumnType("longtext");

                    b.Property<string>("GrpName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GrpType")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Mobile")
                        .HasColumnType("longtext");

                    b.Property<string>("Other")
                        .HasColumnType("longtext");

                    b.Property<string>("Pincode")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<int>("TotalMembers")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Website")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("GrpName");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("GrpProfileId")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IsGrpAdmin")
                        .HasColumnType("longtext");

                    b.Property<string>("MemberMainId")
                        .HasColumnType("longtext");

                    b.Property<int>("MemberProfileId")
                        .HasColumnType("int");

                    b.Property<string>("ModuleId")
                        .HasColumnType("longtext");

                    b.Property<string>("MyCategory")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MemberProfileId");

                    b.HasIndex("GroupId", "MemberProfileId")
                        .IsUnique();

                    b.ToTable("group_members", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.GroupModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IsCustomized")
                        .HasColumnType("longtext");

                    b.Property<string>("MasterProfileId")
                        .HasColumnType("longtext");

                    b.Property<string>("ModuleId")
                        .HasColumnType("longtext");

                    b.Property<string>("ModuleInfo")
                        .HasColumnType("longtext");

                    b.Property<string>("ModuleName")
                        .HasColumnType("longtext");

                    b.Property<string>("ModuleOrderNo")
                        .HasColumnType("longtext");

                    b.Property<string>("ModulePriceRs")
                        .HasColumnType("longtext");

                    b.Property<string>("ModulePriceUS")
                        .HasColumnType("longtext");

                    b.Property<string>("ModuleStaticRef")
                        .HasColumnType("longtext");

                    b.Property<string>("NotificationCount")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("group_modules", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.GroupSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("IsBusiness")
                        .HasColumnType("longtext");

                    b.Property<string>("IsEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("IsFamily")
                        .HasColumnType("longtext");

                    b.Property<string>("IsMob")
                        .HasColumnType("longtext");

                    b.Property<string>("IsPersonal")
                        .HasColumnType("longtext");

                    b.Property<int>("MemberProfileId")
                        .HasColumnType("int");

                    b.Property<string>("ModName")
                        .HasColumnType("longtext");

                    b.Property<string>("ModVal")
                        .HasColumnType("longtext");

                    b.Property<string>("ModuleId")
                        .HasColumnType("longtext");

                    b.Property<string>("ShowEmailOutsideClub")
                        .HasColumnType("longtext");

                    b.Property<string>("ShowEmailSelfClub")
                        .HasColumnType("longtext");

                    b.Property<string>("ShowMobileOutsideClub")
                        .HasColumnType("longtext");

                    b.Property<string>("ShowMobileSelfClub")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("group_settings", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.LeaderboardEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BeneficiaryCount")
                        .HasColumnType("longtext");

                    b.Property<string>("ClubName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("ManHoursCount")
                        .HasColumnType("longtext");

                    b.Property<string>("MembersCount")
                        .HasColumnType("longtext");

                    b.Property<string>("Points")
                        .HasColumnType("longtext");

                    b.Property<string>("ProjectCost")
                        .HasColumnType("longtext");

                    b.Property<string>("RotaractorsCount")
                        .HasColumnType("longtext");

                    b.Property<string>("RotariansCount")
                        .HasColumnType("longtext");

                    b.Property<string>("TotalProjects")
                        .HasColumnType("longtext");

                    b.Property<string>("TrfCount")
                        .HasColumnType("longtext");

                    b.Property<string>("Year")
                        .HasColumnType("longtext");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("ZoneId");

                    b.ToTable("leaderboard_entries", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.MemberProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BloodGroup")
                        .HasColumnType("longtext");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("CategoryId")
                        .HasColumnType("longtext");

                    b.Property<string>("Classification")
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyName")
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyNameHide")
                        .HasColumnType("longtext");

                    b.Property<string>("CountryCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Designation")
                        .HasColumnType("longtext");

                    b.Property<string>("Doa")
                        .HasColumnType("longtext");

                    b.Property<string>("DoaHide")
                        .HasColumnType("longtext");

                    b.Property<string>("Dob")
                        .HasColumnType("longtext");

                    b.Property<string>("DobHide")
                        .HasColumnType("longtext");

                    b.Property<string>("DonorRecognition")
                        .HasColumnType("longtext");

                    b.Property<string>("EmailHide")
                        .HasColumnType("longtext");

                    b.Property<string>("FamilyPic")
                        .HasColumnType("longtext");

                    b.Property<string>("HideMail")
                        .HasColumnType("longtext");

                    b.Property<string>("HideNum")
                        .HasColumnType("longtext");

                    b.Property<string>("HideWhatsnum")
                        .HasColumnType("longtext");

                    b.Property<string>("ImeiMembershipId")
                        .HasColumnType("longtext");

                    b.Property<string>("IsBusinDetVisible")
                        .HasColumnType("longtext");

                    b.Property<string>("IsFamilDetailVisible")
                        .HasColumnType("longtext");

                    b.Property<string>("IsPersonalDetVisible")
                        .HasColumnType("longtext");

                    b.Property<string>("Keywords")
                        .HasColumnType("longtext");

                    b.Property<string>("MemberCountry")
                        .HasColumnType("longtext");

                    b.Property<string>("MemberEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("MemberMobile")
                        .HasColumnType("longtext");

                    b.Property<string>("MemberName")
                        .HasColumnType("longtext");

                    b.Property<string>("MembershipGrade")
                        .HasColumnType("longtext");

                    b.Property<string>("MobileNumHide")
                        .HasColumnType("longtext");

                    b.Property<string>("ProfilePic")
                        .HasColumnType("longtext");

                    b.Property<string>("SecondaryMobileNo")
                        .HasColumnType("longtext");

                    b.Property<string>("SecondaryNumHide")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WhatsappNum")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("member_profiles", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.MerItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExpiryDate")
                        .HasColumnType("longtext");

                    b.Property<string>("FilePath")
                        .HasColumnType("longtext");

                    b.Property<string>("FinanceYear")
                        .HasColumnType("longtext");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .HasColumnType("longtext");

                    b.Property<string>("PublishDate")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<string>("TransType")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("mer_items", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClubDistrictType")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Details")
                        .HasColumnType("longtext");

                    b.Property<string>("ExpiryDate")
                        .HasColumnType("longtext");

                    b.Property<string>("NotifyDate")
                        .HasColumnType("longtext");

                    b.Property<string>("ReadStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("SortDate")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.PastPresident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Designation")
                        .HasColumnType("longtext");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("MemberName")
                        .HasColumnType("longtext");

                    b.Property<int?>("MemberProfileId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("longtext");

                    b.Property<string>("TenureYear")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("MemberProfileId");

                    b.ToTable("past_presidents", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Popup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("popups", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.PopupStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsSeen")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MemberProfileId")
                        .HasColumnType("int");

                    b.Property<int>("PopupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SeenAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PopupId");

                    b.ToTable("popup_statuses", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("service_categories", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.ServiceDirectoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactNo")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactNo2")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("CountryCode1")
                        .HasColumnType("longtext");

                    b.Property<string>("CountryCode2")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("Keywords")
                        .HasColumnType("longtext");

                    b.Property<string>("Latitude")
                        .HasColumnType("longtext");

                    b.Property<string>("Longitude")
                        .HasColumnType("longtext");

                    b.Property<string>("MemberName")
                        .HasColumnType("longtext");

                    b.Property<string>("ModuleId")
                        .HasColumnType("longtext");

                    b.Property<string>("PaxNo")
                        .HasColumnType("longtext");

                    b.Property<int?>("ServiceCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Website")
                        .HasColumnType("longtext");

                    b.Property<string>("Zip")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("ServiceCategoryId");

                    b.ToTable("service_directory_entries", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.SubGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("SubgrpTitle")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("sub_groups", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.SubGroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MemberProfileId")
                        .HasColumnType("int");

                    b.Property<int>("SubGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberProfileId");

                    b.HasIndex("SubGroupId");

                    b.ToTable("sub_group_members", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.TouchbaseSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GrpId")
                        .HasColumnType("longtext");

                    b.Property<string>("GrpName")
                        .HasColumnType("longtext");

                    b.Property<string>("GrpVal")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("touchbase_settings", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceName")
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceToken")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("ImeiMemId")
                        .HasColumnType("longtext");

                    b.Property<string>("ImeiNo")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("LoginType")
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext");

                    b.Property<string>("MobileNo")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Otp")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VersionNo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("MobileNo")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.WebLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullDesc")
                        .HasColumnType("longtext");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("web_links", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ZoneName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("zones", (string)null);
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.AddressDetail", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.MemberProfile", "MemberProfile")
                        .WithMany("Addresses")
                        .HasForeignKey("MemberProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MemberProfile");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Album", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.Group", "Group")
                        .WithMany("Albums")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.AlbumPhoto", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.Album", "Album")
                        .WithMany("Photos")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Announcement", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.Group", "Group")
                        .WithMany("Announcements")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.AttendanceMember", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.AttendanceRecord", "AttendanceRecord")
                        .WithMany("AttendanceMembers")
                        .HasForeignKey("AttendanceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TouchBase.API.Models.Entities.MemberProfile", "MemberProfile")
                        .WithMany()
                        .HasForeignKey("MemberProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttendanceRecord");

                    b.Navigation("MemberProfile");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.AttendanceRecord", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.Group", "Group")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.AttendanceVisitor", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.AttendanceRecord", "AttendanceRecord")
                        .WithMany("AttendanceVisitors")
                        .HasForeignKey("AttendanceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttendanceRecord");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Banner", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.Group", "Group")
                        .WithMany("Banners")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Chapter", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.Zone", "Zone")
                        .WithMany("Chapters")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Club", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.Group", "Group")
                        .WithOne()
                        .HasForeignKey("TouchBase.API.Models.Entities.Club", "GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.DeviceToken", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.User", "User")
                        .WithMany("DeviceTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Document", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.Group", "Group")
                        .WithMany("Documents")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.DocumentReadStatus", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.Document", "Document")
                        .WithMany("ReadStatuses")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TouchBase.API.Models.Entities.MemberProfile", "MemberProfile")
                        .WithMany("DocumentReadStatuses")
                        .HasForeignKey("MemberProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("MemberProfile");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Ebulletin", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.Group", "Group")
                        .WithMany("Ebulletins")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Event", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.Group", "Group")
                        .WithMany("Events")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.EventResponse", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.Event", "Event")
                        .WithMany("Responses")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TouchBase.API.Models.Entities.MemberProfile", "MemberProfile")
                        .WithMany("EventResponses")
                        .HasForeignKey("MemberProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("MemberProfile");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.FamilyMember", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.MemberProfile", "MemberProfile")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("MemberProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MemberProfile");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Feedback", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.Group", "Group")
                        .WithMany("Feedbacks")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Group", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.District", "District")
                        .WithMany("Groups")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("District");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.GroupMember", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TouchBase.API.Models.Entities.MemberProfile", "MemberProfile")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("MemberProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("MemberProfile");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.GroupModule", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.Group", "Group")
                        .WithMany("Modules")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.GroupSetting", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.Group", "Group")
                        .WithMany("GroupSettings")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.LeaderboardEntry", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.Group", "Group")
                        .WithMany("LeaderboardEntries")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TouchBase.API.Models.Entities.Zone", "Zone")
                        .WithMany("LeaderboardEntries")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.MemberProfile", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.User", "User")
                        .WithMany("MemberProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.MerItem", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.Group", "Group")
                        .WithMany("MerItems")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Notification", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.PastPresident", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.Group", "Group")
                        .WithMany("PastPresidents")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TouchBase.API.Models.Entities.MemberProfile", "MemberProfile")
                        .WithMany()
                        .HasForeignKey("MemberProfileId");

                    b.Navigation("Group");

                    b.Navigation("MemberProfile");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Popup", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.Group", "Group")
                        .WithMany("Popups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.PopupStatus", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.Popup", "Popup")
                        .WithMany("Statuses")
                        .HasForeignKey("PopupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Popup");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.ServiceDirectoryEntry", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.Group", "Group")
                        .WithMany("ServiceDirectoryEntries")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TouchBase.API.Models.Entities.ServiceCategory", "ServiceCategory")
                        .WithMany("Entries")
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.SubGroup", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.Group", "Group")
                        .WithMany("SubGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.SubGroupMember", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.MemberProfile", "MemberProfile")
                        .WithMany()
                        .HasForeignKey("MemberProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TouchBase.API.Models.Entities.SubGroup", "SubGroup")
                        .WithMany("Members")
                        .HasForeignKey("SubGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MemberProfile");

                    b.Navigation("SubGroup");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.TouchbaseSetting", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.User", "User")
                        .WithMany("TouchbaseSettings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.WebLink", b =>
                {
                    b.HasOne("TouchBase.API.Models.Entities.Group", "Group")
                        .WithMany("WebLinks")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Album", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.AttendanceRecord", b =>
                {
                    b.Navigation("AttendanceMembers");

                    b.Navigation("AttendanceVisitors");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.District", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Document", b =>
                {
                    b.Navigation("ReadStatuses");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Event", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Group", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Announcements");

                    b.Navigation("AttendanceRecords");

                    b.Navigation("Banners");

                    b.Navigation("Documents");

                    b.Navigation("Ebulletins");

                    b.Navigation("Events");

                    b.Navigation("Feedbacks");

                    b.Navigation("GroupSettings");

                    b.Navigation("LeaderboardEntries");

                    b.Navigation("Members");

                    b.Navigation("MerItems");

                    b.Navigation("Modules");

                    b.Navigation("PastPresidents");

                    b.Navigation("Popups");

                    b.Navigation("ServiceDirectoryEntries");

                    b.Navigation("SubGroups");

                    b.Navigation("WebLinks");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.MemberProfile", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("DocumentReadStatuses");

                    b.Navigation("EventResponses");

                    b.Navigation("FamilyMembers");

                    b.Navigation("GroupMemberships");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Popup", b =>
                {
                    b.Navigation("Statuses");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.ServiceCategory", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.SubGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.User", b =>
                {
                    b.Navigation("DeviceTokens");

                    b.Navigation("MemberProfiles");

                    b.Navigation("Notifications");

                    b.Navigation("TouchbaseSettings");
                });

            modelBuilder.Entity("TouchBase.API.Models.Entities.Zone", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("LeaderboardEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
